[package]
name = "secretgarden"
version = "0.1.0"
authors = ["Jesse Weaver <pianohacker@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
base64 = "0.12"
bincode = "1.3"
byteorder = "1.2"
clap = "3.0.0-beta.1"
rust-crypto = "0.2"
osshkeys = { git = "https://github.com/Leo1003/rust-osshkeys" }
rand = "0.7"
rust-argon2 = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sodiumoxide = "0.2"
ssh-agent = "0.2"
tempfile = "3.1"

[dependencies.openssl-sys]
version = "0.9"
features = [ "vendored" ]
